// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXj2R-kVw07Jm2n9uHYbG9HOQ5KvmJ1fQ',
    appId: '1:38629363666:web:055a13982c76c62164c20b',
    messagingSenderId: '38629363666',
    projectId: 'bus-api-fluther',
    authDomain: 'bus-api-fluther.firebaseapp.com',
    storageBucket: 'bus-api-fluther.firebasestorage.app',
    measurementId: 'G-VRJJM4CDQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB5RWe1n4Nr0HtA6IvWFF8z-F9rJ8KQWw',
    appId: '1:38629363666:android:1a6f34f684d6fc3364c20b',
    messagingSenderId: '38629363666',
    projectId: 'bus-api-fluther',
    storageBucket: 'bus-api-fluther.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJFgLPp-chJVONMnQ4Iv8U-Wa0IjacNo',
    appId: '1:38629363666:ios:c30a3797f58a89ef64c20b',
    messagingSenderId: '38629363666',
    projectId: 'bus-api-fluther',
    storageBucket: 'bus-api-fluther.firebasestorage.app',
    iosBundleId: 'com.kahramanmaras.busDensityMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJFgLPp-chJVONMnQ4Iv8U-Wa0IjacNo',
    appId: '1:38629363666:ios:c30a3797f58a89ef64c20b',
    messagingSenderId: '38629363666',
    projectId: 'bus-api-fluther',
    storageBucket: 'bus-api-fluther.firebasestorage.app',
    iosBundleId: 'com.kahramanmaras.busDensityMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXj2R-kVw07Jm2n9uHYbG9HOQ5KvmJ1fQ',
    appId: '1:38629363666:web:8949e3077cfb04f464c20b',
    messagingSenderId: '38629363666',
    projectId: 'bus-api-fluther',
    authDomain: 'bus-api-fluther.firebaseapp.com',
    storageBucket: 'bus-api-fluther.firebasestorage.app',
    measurementId: 'G-VWBEVQH2E1',
  );
}
